permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Wang Baosheng
  email: suyan0830@gmail.com
  link: http://wbsedu.github.io
  weibo: http://weibo.com/yansu0711
  github: http://github.com/wbsedu

# 站点信息
title: 博客 
description: 博客
url: http://wbsedu.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: 