permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Jianghan Li
  email: wbsedu@outlook.com
  link: http://JianghanLi.github.io
  weibo: http://weibo.com
  github: http://github.com/wbsedu

# 站点信息
title: Blog
description: PEBG
url: http://JianghanLi.github.io
rss_url: /pages/atom.xml
  
# avatar头像及Favicon
avatar: /images/head_pic.PNG 
favicon: /images/head_pic.PNG

# ![images](/images/head_pic.PNG)


# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
#disqus: wbsedu
 # shortname: wbsedu
